### ISSUE TITLE
clean install error

### ISSUE THREAD

**Issue by drveni** [cadriel/fluidd#271]
on command 

cd ~/klipper/

pi@fluiddpi:~/klipper $ make menuconfig

Using default symbol values (no '/home/pi/klipper/.config')
Configuration saved to '/home/pi/klipper/.config'
  Creating symbolic link out/board
Loaded configuration '/home/pi/klipper/.config'
Traceback (most recent call last):
  File "lib/kconfiglib/menuconfig.py", line 3281, in <module>
    _main()
  File "lib/kconfiglib/menuconfig.py", line 661, in _main
    menuconfig(standard_kconfig(__doc__))
  File "lib/kconfiglib/menuconfig.py", line 705, in menuconfig
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
make: *** [Makefile:112: menuconfig] Error 1

what im doing wrong?

download fluidd lastone.. terminal.. login put command and error?

**Comment by drveni** [comment]
fixed with

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales

sudo apt-get install locales
sudo locale-gen en_US.UTF-8
sudo echo "LANG=en_US.UTF-8" > /etc/default/locale


please close topic...

sorry im on GB... tried on native HR and wont works

now im on US.. and works!
sorry for the inconvenience
